import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>New app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>

        <h1 className={styles.title}>Homepage</h1>
        <p className={styles.text}>
          Website intro
        </p>
        <Link href="/plants">
          <a className={styles.btn}>Browse plants</a>
        </Link>

      </div>

    </div>
  )
}
