import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Little Green</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/rose.png" />
      </Head>

      <div>

        <h1 className={styles.title}>Welcome to Little Green!</h1>
        <h2 className={styles.subtitle}>A simple app for plant-lovers using Next.JS</h2>
        <img className={styles.flower} src="https://www.plantlife.org.uk/application/files/cache/9ff3200d7db3607ccf34318052b334cc.jpg" />
        <p className={styles.text}>Click below to see some wild plants!</p>
        <Link href="/plants">
          <a className={styles.btn}>Browse plants</a>
        </Link>

      </div>

    </div>
  )
}
